application:
  port: 8000
  host: "127.0.0.1"
  base_url: "http://127.0.0.1:"

connection:
  min_request_duration: 100
  max_request_duration: 500
  timeout: 2
  max_requests: 5

file:
  file_path: "stats/server_stats.json"
